const { addReleaseSigning } = require('./with-release-signing');

// Excerpt of android/app/build.gradle as generated by `expo prebuild` on SDK 57.
const TEMPLATE = `android {
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug
            minifyEnabled enableMinifyInReleaseBuilds
        }
    }
}
`;

describe('addReleaseSigning', () => {
  const output = addReleaseSigning(TEMPLATE);

  test('adds a release signing config read from the SPANISH_UPLOAD_* Gradle properties', () => {
    expect(output).toContain(`        release {
            if (project.hasProperty('SPANISH_UPLOAD_STORE_FILE')) {
                storeFile file(SPANISH_UPLOAD_STORE_FILE)
                storePassword SPANISH_UPLOAD_STORE_PASSWORD
                keyAlias SPANISH_UPLOAD_KEY_ALIAS
                keyPassword SPANISH_UPLOAD_KEY_PASSWORD
            }
        }`);
  });

  test('signs release builds with the upload key only when the properties are supplied', () => {
    const release = output.slice(output.indexOf('    buildTypes {'));
    expect(release).toContain(
      "signingConfig project.hasProperty('SPANISH_UPLOAD_STORE_FILE') ? signingConfigs.release : signingConfigs.debug",
    );
  });

  test('leaves the debug build type on the debug key', () => {
    const debug = output.slice(
      output.indexOf('    buildTypes {'),
      output.indexOf('        release {\n            // Caution'),
    );
    expect(debug).toContain('signingConfig signingConfigs.debug');
  });

  test('is idempotent', () => {
    expect(addReleaseSigning(output)).toBe(output);
  });

  test('fails loudly when the template layout is not recognised', () => {
    expect(() => addReleaseSigning('android {\n}\n')).toThrow(/signingConfigs/);
  });
});
